### PR TITLE
Style Reset Zoom Button

### PR DESCRIPTION
**Pull request by NicholasHallman**
Functional
 - Manul testing on demo

UX
 - Match daylight
 - [x] Approved by design

9PCy5Q4IOG

### CODE REVIEW

**Review by johngwilkinson — DISMISSED** [review]
Looks good!

Pulled, tested with Narrator and in a narrow window. Didn't notice anything odd.

Except the placement of the button - I've never like that. But out of scope.

**Review by bbabu01 — APPROVED** [review]
LGTM!
Tested locally on Chrome, FF, Edge and used Narrator.
Unrelated to this PR, noticed translations is not working for the button.

**Comment by NicholasHallman** [comment]
> Unrelated to this PR, noticed translations is not working for the button.

Was this on the demo page or on draco stack?

**Comment by NicholasHallman** [comment]
button style

Les translation function bien.

**Review by bbabu01 — APPROVED** [review]
LGTM!
Thanks for confirming translations works.

**Pull request merged**
