### PR TITLE
Use startsWithSearch internal search function to match backend algorithm

### PR DESCRIPTION
**Pull request by Vitalii-Misechko**
[US132923](https://rally1.rallydev.com/#/?detail=/userstory/612183121391&fdp=true): [Adoption][Org Filter] Apply Tree Filter Selection API

Tree has an internal search function that filters nodes by name. It filters using `includes` function. This function should be configurable to match the search algorithm that is used by LMS.

- [x] E2E Tests
  - [x] when the search function is `startsWithSearch` then Tree shows only nodes that start with search string (chars case is ignored). I used Adoption dashboard for this test
  - [x] if search function is not provided then `includesSearch` is used. Tree shows node that contain search string. I used Engagement dashboard.

This PR depends on: https://github.com/BrightspaceUILabs/ou-filter/pull/35

### CODE REVIEW

**Comment by johngwilkinson** [comment]
Should BSI have picked up the upstream change by now? When I do `npm ci` on a clean BSI main branch, then `npm link d2l-adoption-dashboard`, I get `Uncaught SyntaxError: The requested module './../../@brightspace-ui-labs/ou-filter/tree-filter.js' does not provide an export named 'startsWithSearch'` - so I assume I still have the old code. Not sure if there's a better way to test.

**Comment by johngwilkinson** [comment]
Should BSI have picked up the upstream change by now? When I do `npm ci` on a clean BSI main branch, then `npm link d2l-adoption-dashboard`, I get `Uncaught SyntaxError: The requested module './../../@brightspace-ui-labs/ou-filter/tree-filter.js' does not provide an export named 'startsWithSearch'` - so I assume I still have the old code. Not sure if there's a better way to test.

**Comment by Vitalii-Misechko** [comment]
> Should BSI have picked up the upstream change by now? When I do `npm ci` on a clean BSI main branch, then `npm link d2l-adoption-dashboard`, I get `Uncaught SyntaxError: The requested module './../../@brightspace-ui-labs/ou-filter/tree-filter.js' does not provide an export named 'startsWithSearch'` - so I assume I still have the old code. Not sure if there's a better way to test.

I had similar problems until I installed `npm install @brightspace-ui-labs/ou-filter@2.1.4` explicitly for `d2l-adoption-dashboard`
I assume that there is some kind of local cache for npm modules that prevents installing the newest version.

Anyway, the new clean installation of BSI and adoption dashboard works good for me.

**Comment by johngwilkinson** [comment]
> > Should BSI have picked up the upstream change by now? When I do `npm ci` on a clean BSI main branch, then `npm link d2l-adoption-dashboard`, I get `Uncaught SyntaxError: The requested module './../../@brightspace-ui-labs/ou-filter/tree-filter.js' does not provide an export named 'startsWithSearch'` - so I assume I still have the old code. Not sure if there's a better way to test.
> 
> I had similar problems until I installed `npm install @brightspace-ui-labs/ou-filter@2.1.4` explicitly for `d2l-adoption-dashboard` I assume that there is some kind of local cache for npm modules that prevents installing the newest version.
> 
> Anyway, the new clean installation of BSI and adoption dashboard works good for me.

Working for me this morning :shipit:

**Pull request merged**
